output_dir: "./results_fingrag_ch_qwen2.5-vl-72b-instruct"
data_root: "/mnt/shared-storage-user/mineru2-shared/jiayu/data/FinRAGBench-V"
benchmark: "finrag"
extractor_model_name: "MinerU-Agent-CK800"
model_name: "Qwen2.5-VL-72B-Instruct"
base_url: http://localhost:8002/v1
num_threads: 1
reranker_api_base: "http://localhost:8003/"
# limit: 1
# infer_only: true